AWSTemplateFormatVersion: '2010-09-09'
Description: this template deploy a multi-AZ Mysql RDS Instance and read-Replica

Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    Description: DB instance class
    AllowedValues:
      - db.t2.micro
      - db.t2.medium
      - db.t2.large
      - db.m4.large
      - db.r4.large
      

Resources:
  DBInstance:
   Type: AWS::RDS::DBInstance
   Properties:
     DBName: PortfolioDB
     DBInstanceClass: db.t2.micro
     Engine: MySQL
     MasterUsername: admin
     MasterUserPassword: admin2369
     AllocatedStorage: 20
     StorageType: gp2
     MultiAZ: True
     DBSubnetGroupName: !Ref DBSubnetGroup
     PubliclyAccessible: false
     VPCSecurityGroups:
       - !Ref DBSecurityGroup
     Tags:
       - Key: Name
         Value: MyRDSInstance

  DBSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
    GroupDescription: Open database for access
    VpcId: !ImportValue newstack1-VPC
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        !ImportValue App-SecurityGroupWeb
    Tags:
      - Key: Name
        Value: MyDBSecurityGroup
      
  DBSubnetGroup:
   Type: AWS::RDS::DBSubnetGroup
   Properties:
     DBSubnetGroupDescription: "My DB Subnet Group"
     SubnetIds:
       - !ImportValue newstack1-PrivateSubnetC
       - !ImportValue newstack1-PrivateSubnetD
     Tags:
       - Key: Name
         Value: MyDBSubnetGroup

  ReplicaDB:
    Type: AWS::RDS::DBInstance
    Properties:
      SourceDBInstanceIdentifier: !Ref DBInstance
      DBInstanceClass: !Ref 'DBInstanceClass'
      Tags:
      - Key: Name
        Value: Read Replica Database
